echo "Running tests:        "
echo "                      "
echo "----------------------"
echo "|                    |"
echo "|     First test     |"
echo "|                    |"
echo "----------------------"
echo "                      "
printf "Hello | there!\nThis | is | a | test | file!\noh | yeah!! :)" > test1.txt
echo "contents of file: "
echo "                      "
printf "Hello | there!\nThis | is | a | test | file\noh | yeah!! :)\n"
echo "                      "
echo "./sed \"test1.txt\" \" | \" \"...\""
./sed "test1.txt" " | " "..."
echo "                      "
echo "contents of new file (test1.txt.replace): "
echo "                      "
cat test1.txt.replace
echo
echo "                      "
echo "----------------------"
echo "|                    |"
echo "|     Second test    |"
echo "|                    |"
echo "----------------------"
echo "                      "
printf "sdfsjfksldfdjsfdj999dsfdsflkfjl999sdfsdlfkjd999" > test2.txt
echo "contents of file: "
echo "                      "
printf "sdfsjfksldfdjsfdj999dsfdsflkfjl999sdfsdlfkjd999\n"
echo "                      "
echo "./sed \"test2.txt\" \"999\" \"++++\""
./sed "test2.txt" "999" "++++"
echo "                      "
echo "contents of new file (test2.txt.replace): "
echo "                      "
cat test2.txt.replace
echo
echo "                      "
echo "----------------------"
echo "|                    |"
echo "|     Third test     |"
echo "|                    |"
echo "----------------------"
echo "                      "
printf "hihihihihihihihihihi:Ohihihihihihi" > test3.txt
echo "contents of file: "
echo "                      "
printf "hihihihihihihihihihi:Ohihihihihihi\n"
echo "                      "
echo "./sed \"test3.txt\" \"hi\" \"  \""
./sed "test3.txt" "hi" "  "
echo "                      "
echo "contents of new file (test3.txt.replace): "
echo "                      "
cat test3.txt.replace